#!/bin/bash
set -euo pipefail

cd "$(dirname "$0")"

build_one() {
  local name=$1
  rm -f $name.aux \
        $name.dvi \
        $name.log \
        $name.out \
        $name.toc

  latex $name.tex
  latex $name.tex
  pdflatex $name.tex
}

build_one data-science-in-ten-minutes
build_one solutions
